### ISSUE TITLE
system_load measurement missing

### ISSUE THREAD

**Issue by skynet** [influxdb/telegraf#128]
Missing system_load measurement with a new telegraf-0.1.5-1.x86_64.rpm and InfluxDB v0.9.3-rc1

**Comment by skynet** [comment]
Looks like 
```
# Read metrics about system load
[system]
  # no configuration
```
was removed from telegraf.conf
Any special reason for this change?

**Comment by sparrc** [comment]
There was no particular reason to remove it, I just wanted telegraf's default config entries to be fairly stream-lined and without external dependencies (such as a mysql server). So that being said, system load is probably one that actually should stay.

I'll add it back in for the next release :+1:, thanks for the feedback!

**Comment by skynet** [comment]
Thanks for the hard work. Really appreciated.
