### ISSUE TITLE
I think that is a bug in telegraf

### ISSUE THREAD

**Issue by prsolucoes** [influxdb/telegraf#151]
Hi,

None of data is exported to my InfluxDB, and after see the log i get:

```
2015/08/28 14:33:41 Error in plugin [io]: error getting disk io info: open /proc/diskstats: no such file or directory
2015/08/28 14:33:41 Error in output [influxdb]: unable to parse 'disk_total,fstype=reiserfs,host=vps371,path=/ value=107374182400i': invalid number
2015/08/28 14:33:41 Error encountered flushing outputs
``` 

I only enable mysql and server outputs (mem, cpu, ...)

What can be wrong?

Edit:
Link to screenshot:
https://www.dropbox.com/s/j985ef9uwhih5wb/Screenshot%202015-08-28%2014.34.45.png?dl=0

InfluxDB: Last Version: 0.9.2
Telegraf: Last version (i made a clone and build with Go)

**Comment by jipperinbham** [comment]
What version of InfluxDB and telegraf are you running?

**Comment by prsolucoes** [comment]
I have edited the post with infos.

**Comment by sparrc** [comment]
@prsolucoes your problem is that your version of telegraf is incompatible with your version of InfluxDB, you will need to downgrade to telegraf 0.1.4 or upgrade your Influx instance to 0.9.3

see the README for more info: https://github.com/influxdb/telegraf#linux-packages-for-debianubuntu-and-rhelcentos

**Comment by prsolucoes** [comment]
Problems solved after update. Thanks.
