### ISSUE TITLE
Derived metrics

### ISSUE THREAD

**Issue by deanefrati** [influxdb/telegraf#171]
Until influxdb can support lead and lag functions (https://github.com/influxdb/influxdb/issues/142, https://github.com/influxdb/influxdb/issues/143). It would be great if telegraf would provide more derived metrics and not just the straight values in the various /proc files. For example it would be great if the disk plugin would provide information similar to iostat reads/s writes/s await etc. Similarly it would be great if the network plugin would do the same, t/kbps r/kbps drop rate etc.
Really this applies to most plugins that report straight values and not percentage values the postgres plugin can be enhanced the same and i'm sure others as well.

**Comment by sparrc** [comment]
I agree, at the moment the "system" plugins are a bit basic and need to provide more complete information.

**Comment by sparrc** [comment]
@deanefrati after thinking this over a bit more and discussing with other people at Influx, I think that we probably want to use a different approach. Rather than growing the database with derived metrics, InfluxDB can be queried to get the derived metrics from raw counters.

Take the `net` plugin, for example, an InfluxDB query like below will give you the kbps rate using only the bytes_recv data:
```
SELECT derivative(value,1s)/1024 FROM net_bytes_recv
```

I think that this does need to be documented better, and probably even worthy of a blog post

**Comment by sparrc** [comment]
Closing the issue, feel free to re-open if you don't think that this covers your use-case and we can discuss further

**Comment by deanefrati** [comment]
thanks @sparrc that works for me and is actually elegant for metrics that can be calculated from only one datapoint in one series. However what about ones that requires multiple data points for example % CPU used (i know you already implemented that but just an example) In order to calculate that i will need to have a way to fetch that last two consecutive datapoints from influx (lead, lag) but that isn't currently available in influx. Also what about situations where the derived metric needs to come from more than one series (IO is a good example for this), i couldn't find any documentations about joins in influx... does the concept exist? Sorry if these are basic questions i'm kind of new to influx and telegraf. Really like both but so far find it a bit difficult to find documentation and/or easily derive more meaningful stats.

**Comment by sparrc** [comment]
Yes I agree about calculating stats based on multiple measurement, there is actually an open case about that here: https://github.com/influxdb/telegraf/issues/152

This would basically be calling for any plugin to consolidate all of it's values as fields in a single measurement. It's a pretty large and breaking change, but it's looking like people in the community would like to have this, which would make something like this possible: `SELECT idle+busy FROM cpu`. If possible, could you also throw in your 2 cents to that case if it's something you would like to see as well?

In regards to other derived stats, our approach is probably going to be to limit those where a simple DB query is possible. CPU usage percent is one where I decided it was okay, because that measurement is quite a bit more complicated than just taking a derivative. I think we're going to have to manage which derived stats are acceptable on a case-by-case basis.

**Comment by wongster80** [comment]
Hi,

I'm trying to get write and read per seconds statistics from the "diskio" measurement with the Influx SQL below, but the graph does not seem to be the correct representation has it shows negative number in Grafana:
SELECT derivative("writes", 1s) FROM "diskio" 

Can someone suggest how I can get reads/s and writes/s from "diskio" measurement?

**Comment by beckettsean** [comment]
@wongster80 I replied also to your post to influxdb@googlegroups.com, but this is precisely the use case for the `NON_NEGATIVE_DERIVATIVE` function, which prevents counter resets from generating a negative slope.
