### ISSUE TITLE
Mem plugin issue - Telegraph 0.1.8

### ISSUE THREAD

**Issue by JulienChampseix** [influxdb/telegraf#179]
Hi,

After upgrading telegraf to 0.1.8, we got this error:

Error in output [influxdb]: write failed: field type conflict: input field "value" on measurement "swap_total" is type int64, already exists as type float
Error in output [influxdb]: write failed: field type conflict: input field "value" on measurement "mem_total" is type int64, already exists as type float

How to fix it ?

**Comment by sparrc** [comment]
@JulienChampseix What is your version of InfluxDB and what version of Telegraf did you upgrade from?

My best guess is that you were using telegraf 0.1.4 or lower with InfluxDB 0.9.3+, this is documented as being incompatible here: https://github.com/influxdb/telegraf#installation

Because of the breaking line-protocol change, this would mean that your integer values from Telegraf would be interpreted by Influxdb as floats. Now that you've upgraded telegraf, the integers are being properly parsed as integers, leading to the incompatability.

Unfortunately the only easy option would be to drop the affected measurements from influxdb and start over: https://influxdb.com/docs/v0.9/query_language/data_exploration.html#dropping-measurements-series-and-databases

Beyond that, you can export the measurements and re-parse them into influxdb manually, but there is no easy way to accomplish that. I'm sorry about the inconvenience, but at least know that this breaking change was made to avoid this situation happening in the future

**Comment by sparrc** [comment]
I'm going to assume that solves it, but please feel free to re-open if I was off-base, thank you for the report!
