### ISSUE TITLE
server tag error for plugins

### ISSUE THREAD

**Issue by takaidohigasi** [influxdb/telegraf#201]
* version: 0.1.8
* summary: when server tag is null, plugin fails. server tag seems to be set null by default.

config sample

```
# NG
[mysql]
servers = ["localhost"]

# NG
[mysql]
# servers = ["localhost"]

# OK(workaround)
[mysql]
servers = ["root:@tcp(127.0.0.1:3306)/"]
```

error log

```
2015/09/16 19:37:16 ERROR: unable to parse 'mysql_aborted_clients,host=taka-h.local,server= value=756i': missing tag value
2015/09/16 19:37:16 Error encountered flushing outputs
```

**Comment by takaidohigasi** [comment]
Related code was wrong.

I'm trying to fix code.
https://github.com/influxdb/telegraf/blob/master/agent.go#L309-L311

**Comment by takaidohigasi** [comment]
How blank tag value should be handled?

> [server=""] mysql_threads_created value=5
> [server=""] mysql_threads_running value=1

Should it be to store with a blank tag value?

**Comment by sparrc** [comment]
I believe that blank tags should be ignored and dropped

**Comment by sparrc** [comment]
But I don't think this is an issue in tsdb, I think it's only an issue with the mysql plugin trying to make blank tags.

Server tag is not set to null, but it looks like it's being truncated to "" when set to "localhost" (because of what appears to be a strange behavior with the go sql library wanting a blank server string instead of localhost)
